global:
  scrape_interval:     5s 
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'apache-exporter'
    scheme: http
    static_configs:
    - targets: ['cdnapi:9117']
      labels: {'host': 'cdn api'}
