global:
  scrape_interval:     5s 
  evaluation_interval: 5s 

rule_files:
  - '/etc/prometheus/alert.rules'

scrape_configs:
  - job_name: 'apache-exporter'
    scheme: http
    static_configs:
    - targets: ['comerade-laov6410.kermit.itn.intraorange']
      labels: {'host': 'cOmerade'}

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']
